config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :posts
  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params 
          params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
  
      def acount_update_params 
          params.require(:user).permit(:name,:email, :password, :password_confirmation, :current_password)
    end
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <%= link_to 'Stay In Touch', root_path, class: 'navbar-brand' %>
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to 'Timeline', posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'AllUsers', users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <button type="button" class="btn btn-primary">
                    <%= link_to 'Sign_out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </button>
            </li>
        </ul>
    <%else%>
        <li>
            <%= link_to 'Sign_up', new_user_registration_path, class: 'btn btn-secondary' %>
            <%= link_to 'Sign_in', user_session_path, class: 'btn btn-secondary' %>
        </li>    
    <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |e|%>
    <%= link_to 'User', user_path(e)%>
<% end %>

app/views/users/show.html.erb
<h1><%=@user.name %><h1>